import {
  NEWS_CATEGORIES,
  NEWS_PROVIDERS,
  DEFAULT_NEWS_PROVIDER_IDS,
  DEFAULT_NEWS_CATEGORY_IDS,
  NEWS_CARD_COUNTS,
  NEWS_HEADLINE_OPACITIES,
  NEWS_MIN_REFETCH_MS,
  NEWS_REFRESH_INTERVALS,
} from "./newsFeeds.js";
import { WEATHER_API_CONFIG, WMO_WEATHER_CODES } from "./weather.js";
import { WALLPAPER_CONFIG } from "./wallpaper.js";
import { QUOTES } from "./quotes.js";
import { SEARCH_PROVIDERS, SEARCH_SUGGESTIONS } from "./searchEngines.js";
import { GOOGLE_APPS } from "./apps.js";
import { AI_TOOLS } from "./aiTools.js";
import { SOCIAL_LINKS } from "./socials.js";
import { FONT_OPTIONS } from "./fonts.js";

export const CONFIG = {
  defaults: {
    clockFormat: "24",
    clockType: "digital",
    showDate: true,
    tempUnit: "metric",
    widgetControl: "all",
    showTodo: true,
    showApps: true,
    shortcutsPosition: "bottom",
    shortcutsDisplayMode: "shortcuts",
    fontFamily: "outfit",
    newsEnabled: true,
    newsPermissionModelVersion: 1,
    newsBadgeDismissed: false,
    newsProviderIds: [...DEFAULT_NEWS_PROVIDER_IDS],
    newsCategoryIds: [...DEFAULT_NEWS_CATEGORY_IDS],
    newsShowHeadlines: true,
    newsHeadlineOpacity: 50,
    newsTotalCards: 5,
    newsRefreshIntervalMinutes: 5,
    newsPosition: "bottom",
    newsConsentRemembered: true,
    newsCache: {
      version: 2,
      imageParserVersion: 6,
      ageMinutes: 0,
      selectionKey: "",
      lastAttemptAt: 0,
      fetchedAt: 0,
      items: [],
      failures: [],
    },
    showAiTools: true,
    showEditableText: true,
    disableAnimations: false,
    disableAnimationsToggleCount: 0,
    glowEffect: false,
    glowDefaultOffMigrated: false,
    glassmorphismUseCount: 0,
    fontFamilyUseCount: 0,
    randomBgMode: "random",
    randomBgSchedule: "refresh",
    randomBgScheduleBadgeDismissed: true,
    randomBgRefreshWarningDismissed: true,
    randomBgLastChangedAt: 0,
    randomBgLastChangedDate: "",
    randomBgCurrentPreview: "",
    settingsShortcutUseCount: 0,
    miniSettingsShortcutUseCount: 0,
    darkModeToggleUseCount: 0,
    weatherLocationSaveCount: 0,
    lavenderMistThemeUseCount: 0,
    dawnBloomThemeUseCount: 0,
    mistralToolUseCount: 0,
    tiktokToolUseCount: 0,
    perplexityUseCount: 0,
    themeGeneratorUseCount: 0,
    todos: [
      {
        id: "vv-1",
        text: "欢迎使用 VerseVibe 动态仪表盘",
        completed: false,
        pinned: true,
      },
      {
        id: "vv-2",
        text: "点击右上角设置图标自定义壁纸、天气与小部件",
        completed: false,
        pinned: false,
      },
      {
        id: "vv-3",
        text: "双击中心问候语可更改您的专属称呼",
        completed: false,
        pinned: false,
      },
    ],
    welcomeText: "点击编辑问候语",
    searchProvider: { id: "baidu", type: "engines" },
    googleAiSearchActive: false,
    googleAiSearchUsed: false,
    googleAiSearchHintShownCount: 0,
    searchSuggestionMode: "history-only",
    searchSuggestionProxyUrl: "",
    searchSuggestionConsentRemembered: true,
    searchSuggestionBadgeDismissed: false,
    customSearchEngines: [],
    customAiTools: [],
    customSocialLinks: [],
    customApps: [],
    googleAppOverrides: {},
    hiddenApps: {},
    appsEditHintCount: 0,
    gradientColorThemeId: "",
    gradientColor1: "",
    gradientColor2: "",
    hiddenTools: {},
    hiddenToolsDefaultsMigrated: false,
    autoTheme: false,
    zenMode: false,
    zenNoticeAcknowledged: false,
    miniSettingsHintShown: false,
    themeGenerationHintShown: false,
    miniSettingsOpenCount: 0,
    fullSettingsEverOpened: false,
    darkMode: true,
    darkSignalBackgroundActive: false,
    darkSignalBackgroundEverActivated: false,
    darkSignalBackgroundHintCount: 0,
    transparencyActive: true,
    grayscaleActive: false,
    normalThemeId: "default-dark",
    linkTargets: {
      ai: "_blank",
      apps: "_blank",
      shortcuts: "_blank",
      searchOpen: "_blank",
      news: "_blank",
    },
    searchHistory: [],
    searchHistoryPaused: false,
    searchAutoDeleteDays: 365,
    commandPaletteShortcutUseCount: 0,
    commandUsage: {},
  },
  paths: {
    icons: "/dashboard-assets/icons/",
    search: "/dashboard-assets/search-tools/",
    apps: "/dashboard-assets/google-apps/",
    ai: "/dashboard-assets/ai-tools/",
    social: "/dashboard-assets/socials/",
  },
};

export const COMMAND_PALETTE_SHORTCUT_USE_LIMIT = 3;

// Search suggestion modes
export const SEARCH_SUGGESTION_MODES = Object.freeze({
  HISTORY_ONLY: "history-only",
  HISTORY_ONLINE: "history-online",
  HISTORY_CUSTOM: "history-custom",
});

// Keyboard defaults
export const DEFAULT_KEY_MAP = {
  todo: { key: "t", enabled: true },
  ai: { key: "a", enabled: true },
  apps: { key: "g", enabled: true },
  settings: { key: "s", enabled: true },
  miniSettings: { key: "m", enabled: true },
  search: { key: "/", enabled: true },
  clock: { key: "c", enabled: false },
  date: { key: "d", enabled: false },
  autoTheme: { key: "e", enabled: false },
  tempDisplay: { key: "f", enabled: false },
  hideGreetings: { key: "j", enabled: false },
  showEditableText: { key: "k", enabled: false },
  numKeys: { key: "1-9", enabled: true, fixed: true },
  zen: { key: "z", enabled: true, fixed: true },
  voice: { key: "v", enabled: true, fixed: true },
};

// Re-export all config modules
export {
  NEWS_CATEGORIES,
  NEWS_PROVIDERS,
  DEFAULT_NEWS_PROVIDER_IDS,
  DEFAULT_NEWS_CATEGORY_IDS,
  NEWS_CARD_COUNTS,
  NEWS_HEADLINE_OPACITIES,
  NEWS_MIN_REFETCH_MS,
  NEWS_REFRESH_INTERVALS,
  WEATHER_API_CONFIG,
  WMO_WEATHER_CODES,
  WALLPAPER_CONFIG,
  QUOTES,
  SEARCH_PROVIDERS,
  SEARCH_SUGGESTIONS,
  GOOGLE_APPS,
  AI_TOOLS,
  SOCIAL_LINKS,
  FONT_OPTIONS,
};
